"resources"
{
"maps/cs_belair73.res" "file"
"maps/cs_belair73.bsp" "file"
"maps/cs_belair73.txt" "file"
"maps/cs_belair73.nav" "file"

"materials/belairtextures/arbregenealogique.vmt" "file"
"materials/belairtextures/arbregenealogique.vtf" "file"
"materials/belairtextures/belair.vmt" "file"
"materials/belairtextures/belair.vtf" "file"
"materials/belairtextures/green.vmt" "file"
"materials/belairtextures/green.vtf" "file"
"materials/belairtextures/pierreserre.vmt" "file"
"materials/belairtextures/pierreserre.vtf" "file"
"materials/belairtextures/wallpaperSAMDS.vmt" "file"
"materials/belairtextures/wallpaperSAMDS.vtf" "file"
"materials/belairtextures/white.vmt" "file"
"materials/belairtextures/white.vtf" "file"
"materials/belairtextures/yellow.vmt" "file"
"materials/belairtextures/yellow.vtf" "file"
"materials/belairtextures/murdepierre.vmt" "file"
"materials/belairtextures/murdepierre.vtf" "file"
"materials/belairtextures/tomettes.vmt" "file"
"materials/belairtextures/tomettes.vtf" "file"
"materials/belairtextures/saumon.vmt" "file"
"materials/belairtextures/saumon.vtf" "file"
"materials/belairtextures/porte.vmt" "file"
"materials/belairtextures/porte.vtf" "file"
"materials/belairtextures/murfacade.vmt" "file"
"materials/belairtextures/murfacade.vtf" "file"
"materials/belairtextures/rampeb.vmt" "file"
"materials/belairtextures/rampeb.vtf" "file"
"materials/belairtextures/ramped.vmt" "file"
"materials/belairtextures/ramped.vtf" "file"

"materials/belairtextures/chemin1.vmt" "file"
"materials/belairtextures/chemin2.vmt" "file"
}